aws_access_key = "AKIAV2GARFLTZFIFWP76"
aws_secret_key = "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"
aws_region="us-east-1"
vpc-cidr="10.1.0.0/16"
public_subnet1_cidr="10.1.1.0/24"
public_subnet1_cidr="10.1.2.0/24"
public_subnet1_cidr="10.1.3.0/24"
private_subnet_cidr="10.1.20.0/24"
vpc_name = "terraform-aws-testing"
IGW_name = "terraform-qws-igw"
public_subnet1_name = "Terraform_Public_Subnet1_testing"
public_subnet1_name = "Terraform_Public_Subnet2_testing"
public_subnet1_name = "Terraform_Public_Subnet3_testing"
public_subnet1_name = "Terraform_Private_Subnet_testing"
Main_Routing_Table = "Terraform_Main_table-testing"
key_name = "mytestingkey"
environment = "dev"

